# Generated by Django 3.1.5 on 2021-01-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTable',
            fields=[
                ('board_no', models.AutoField(primary_key=True, serialize=False)),
                ('board_main', models.TextField()),
                ('board_content', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'board_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberGrade',
            fields=[
                ('mem_grade', models.IntegerField(primary_key=True, serialize=False)),
                ('class_field', models.CharField(db_column='class', max_length=20)),
            ],
            options={
                'db_table': 'member_grade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('mem_no', models.AutoField(primary_key=True, serialize=False)),
                ('mem_name', models.CharField(max_length=30)),
                ('mem_email', models.CharField(max_length=50, unique=True)),
                ('password', models.TextField()),
                ('stu_num', models.IntegerField(unique=True)),
                ('mem_phone', models.CharField(max_length=15, unique=True)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'member_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_no', models.AutoField(primary_key=True, serialize=False)),
                ('mem_no', models.IntegerField()),
                ('review_comment', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
    ]
